import type {
  AuditLog,
  Department,
  Employee,
  Permission,
  Role,
  RoleDefinition,
  User,
  Visit,
  Visitor,
} from "./types";

export const ROLE_DEFINITIONS: RoleDefinition[] = [
  {
    key: "guard",
    label: "نگهبان",
    permissions: [
      "visits.create",
      "visits.exit",
      "visits.view",
      "visitors.search",
      "dashboard.view",
    ],
  },
  {
    key: "manager",
    label: "مدیر امنیت",
    permissions: [
      "visits.view",
      "visitors.search",
      "reports.view",
      "reports.export",
      "audit.view",
      "dashboard.view",
    ],
  },
  {
    key: "admin",
    label: "مدیر سیستم",
    permissions: [
      "visits.create",
      "visits.exit",
      "visits.view",
      "visitors.search",
      "reports.view",
      "reports.export",
      "audit.view",
      "users.manage",
      "roles.manage",
      "departments.manage",
      "employees.manage",
      "settings.manage",
      "dashboard.view",
    ],
  },
];

export function permissionsForRole(role: Role): Permission[] {
  return ROLE_DEFINITIONS.find((r) => r.key === role)?.permissions ?? [];
}

export function roleLabel(role: Role): string {
  return ROLE_DEFINITIONS.find((r) => r.key === role)?.label ?? role;
}

export const MOCK_USERS: User[] = [
  {
    id: "u-1",
    username: "guard",
    fullName: "علی احمدی",
    role: "guard",
    active: true,
    createdAt: "2025-01-05T08:00:00Z",
  },
  {
    id: "u-2",
    username: "manager",
    fullName: "مریم رضایی",
    role: "manager",
    active: true,
    createdAt: "2025-01-05T08:00:00Z",
  },
  {
    id: "u-3",
    username: "admin",
    fullName: "حسین موسوی",
    role: "admin",
    active: true,
    createdAt: "2025-01-05T08:00:00Z",
  },
  {
    id: "u-4",
    username: "guard2",
    fullName: "رضا کریمی",
    role: "guard",
    active: true,
    createdAt: "2025-02-10T08:00:00Z",
  },
];

export const MOCK_DEPARTMENTS: Department[] = [
  { id: "d-1", name: "حوزه ریاست", code: "RIA", floor: "طبقه ۵", active: true },
  { id: "d-2", name: "اداره مالی", code: "FIN", floor: "طبقه ۳", active: true },
  { id: "d-3", name: "منابع انسانی", code: "HR", floor: "طبقه ۲", active: true },
  { id: "d-4", name: "فناوری اطلاعات", code: "IT", floor: "طبقه ۴", active: true },
  { id: "d-5", name: "روابط عمومی", code: "PR", floor: "طبقه ۱", active: false },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "e-1",
    fullName: "دکتر محمد صادقی",
    nationalCode: "0012345678",
    position: "رئیس",
    departmentId: "d-1",
    phone: "09121112233",
    active: true,
  },
  {
    id: "e-2",
    fullName: "زهرا حسینی",
    nationalCode: "0023456789",
    position: "کارشناس ارشد",
    departmentId: "d-2",
    phone: "09122223344",
    active: true,
  },
  {
    id: "e-3",
    fullName: "امیر نجفی",
    nationalCode: "0034567890",
    position: "مدیر منابع انسانی",
    departmentId: "d-3",
    phone: "09123334455",
    active: true,
  },
  {
    id: "e-4",
    fullName: "سارا مرادی",
    nationalCode: "0045678901",
    position: "مدیر IT",
    departmentId: "d-4",
    phone: "09124445566",
    active: true,
  },
  {
    id: "e-5",
    fullName: "بهرام کاظمی",
    nationalCode: "0056789012",
    position: "کارشناس شبکه",
    departmentId: "d-4",
    phone: "09125556677",
    active: true,
  },
];

export const MOCK_VISITORS: Visitor[] = [
  {
    id: "v-1",
    nationalCode: "0067890123",
    fullName: "جواد رحیمی",
    firstName: "جواد",
    lastName: "رحیمی",
    fatherName: "اکبر",
    birthDate: "1365/03/12",
    gender: "male",
    phone: "09131112233",
    source: "civil_registry",
    verified: true,
    lastVerifiedAt: "2026-06-01T09:00:00Z",
    createdAt: "2026-06-01T09:00:00Z",
  },
  {
    id: "v-2",
    nationalCode: "0078901234",
    fullName: "فاطمه اکبری",
    firstName: "فاطمه",
    lastName: "اکبری",
    fatherName: "رضا",
    birthDate: "1370/07/22",
    gender: "female",
    phone: "09132223344",
    source: "civil_registry",
    verified: true,
    lastVerifiedAt: "2026-06-05T10:00:00Z",
    createdAt: "2026-06-05T10:00:00Z",
  },
  {
    id: "v-3",
    nationalCode: "0089012345",
    fullName: "میلاد شریفی",
    firstName: "میلاد",
    lastName: "شریفی",
    fatherName: "حسن",
    birthDate: "1372/11/03",
    gender: "male",
    phone: "09133334455",
    source: "manual",
    verified: false,
    createdAt: "2026-07-01T08:30:00Z",
  },
  {
    id: "v-4",
    nationalCode: "0090123456",
    fullName: "نرگس قاسمی",
    firstName: "نرگس",
    lastName: "قاسمی",
    fatherName: "علی",
    birthDate: "1368/01/15",
    gender: "female",
    phone: "09134445566",
    source: "civil_registry",
    verified: true,
    lastVerifiedAt: "2026-07-10T11:20:00Z",
    createdAt: "2026-07-10T11:20:00Z",
  },
];

const now = new Date();
const iso = (offsetMinutes: number) =>
  new Date(now.getTime() - offsetMinutes * 60 * 1000).toISOString();

export const MOCK_VISITS: Visit[] = [
  {
    id: "vs-1",
    visitNumber: "V-1404-000101",
    visitorId: "v-1",
    departmentId: "d-1",
    employeeId: "e-1",
    purpose: "جلسه اداری",
    entryTime: iso(45),
    exitTime: null,
    status: "inside",
    guardId: "u-1",
    badgeNumber: "B-014",
    companionsCount: 0,
  },
  {
    id: "vs-2",
    visitNumber: "V-1404-000102",
    visitorId: "v-2",
    departmentId: "d-2",
    employeeId: "e-2",
    purpose: "پیگیری پرونده مالی",
    entryTime: iso(120),
    exitTime: null,
    status: "inside",
    guardId: "u-1",
    badgeNumber: "B-015",
    vehiclePlate: "۱۲ ب ۳۴۵ - ایران ۱۱",
    companionsCount: 1,
  },
  {
    id: "vs-3",
    visitNumber: "V-1404-000103",
    visitorId: "v-3",
    departmentId: "d-4",
    employeeId: "e-5",
    purpose: "پشتیبانی فنی",
    entryTime: iso(360),
    exitTime: iso(280),
    status: "exited",
    guardId: "u-4",
    badgeNumber: "B-012",
    companionsCount: 0,
  },
  {
    id: "vs-4",
    visitNumber: "V-1404-000104",
    visitorId: "v-4",
    departmentId: "d-3",
    employeeId: "e-3",
    purpose: "مصاحبه استخدامی",
    entryTime: iso(1440),
    exitTime: iso(1320),
    status: "exited",
    guardId: "u-1",
    badgeNumber: "B-009",
    companionsCount: 0,
  },
  {
    id: "vs-5",
    visitNumber: "V-1404-000105",
    visitorId: "v-1",
    departmentId: "d-4",
    employeeId: "e-4",
    purpose: "بازدید فنی",
    entryTime: iso(2880),
    exitTime: iso(2820),
    status: "exited",
    guardId: "u-4",
    badgeNumber: "B-005",
    vehiclePlate: "۲۲ ج ۶۷۸ - ایران ۲۲",
    companionsCount: 2,
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "a-1",
    userId: "u-1",
    action: "ثبت ورود",
    entity: "Visit",
    entityId: "vs-1",
    timestamp: iso(45),
    ip: "192.168.1.10",
  },
  {
    id: "a-2",
    userId: "u-1",
    action: "ثبت ورود",
    entity: "Visit",
    entityId: "vs-2",
    timestamp: iso(120),
    ip: "192.168.1.10",
  },
  {
    id: "a-3",
    userId: "u-4",
    action: "ثبت خروج",
    entity: "Visit",
    entityId: "vs-3",
    timestamp: iso(280),
    ip: "192.168.1.11",
  },
  {
    id: "a-4",
    userId: "u-3",
    action: "ورود به سیستم",
    entity: "Auth",
    entityId: "u-3",
    timestamp: iso(500),
    ip: "192.168.1.5",
  },
  {
    id: "a-5",
    userId: "u-3",
    action: "ایجاد کاربر جدید",
    entity: "User",
    entityId: "u-4",
    timestamp: iso(2000),
    ip: "192.168.1.5",
  },
];
